/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#351000",
        "surface-container-highest": "#eae1da",
        "surface-container": "#f6ece6",
        "primary-container": "#b15f00",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#2f1500",
        "primary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed-variant": "#8f0042",
        "secondary-fixed": "#ffdbcc",
        "surface-tint": "#904d00",
        "surface-bright": "#fff8f5",
        "on-secondary-container": "#794227",
        "primary": "#8d4b00",
        "on-tertiary-fixed": "#3f0019",
        "tertiary-fixed": "#ffd9e0",
        "secondary": "#895033",
        "on-surface": "#1f1b17",
        "tertiary": "#b40b56",
        "surface-dim": "#e2d8d2",
        "primary-fixed": "#ffdcc3",
        "background": "#fff8f5",
        "tertiary-container": "#d7306f",
        "on-background": "#1f1b17",
        "on-secondary-fixed-variant": "#6d391e",
        "inverse-surface": "#342f2b",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb694",
        "secondary-container": "#feb28f",
        "inverse-on-surface": "#f9efe8",
        "on-tertiary-container": "#fffbff",
        "on-primary-container": "#fffbff",
        "outline-variant": "#dbc2b0",
        "surface-container-low": "#fcf2eb",
        "surface-container-high": "#f0e6e0",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "outline": "#887364",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#6e3900",
        "tertiary-fixed-dim": "#ffb1c3",
        "surface-variant": "#eae1da",
        "on-surface-variant": "#554336",
        "error-container": "#ffdad6",
        "surface": "#fff8f5",
        "inverse-primary": "#ffb77d"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Be Vietnam Pro"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
